<Project>
    <ItemGroup>
        <PackageVersion Include="AWSSDK.S3" Version="4.0.6.4" />
        <PackageVersion Include="BigGustave" Version="1.0.6" />
        <PackageVersion Include="Jab" Version="0.11.0" />
        <PackageVersion Include="MemoryPack" Version="1.21.4" />
        <PackageVersion Include="Microsoft.AspNetCore.App" Version="2.2.8" />
        <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8" />
        <PackageVersion Include="Microsoft.Extensions.ApiDescription.Server" Version="9.0.8" />
        <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="9.0.8" />
        <PackageVersion Include="Microsoft.Extensions.FileProviders.Embedded" Version="9.0.8" />
        <PackageVersion Include="Microsoft.Extensions.Logging" Version="9.0.8" />
        <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.8" />
        <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="9.0.8" />
        <PackageVersion Include="Microsoft.Extensions.ObjectPool" Version="9.0.8" />
        <PackageVersion Include="Olve.Logging" Version="0.32.2" />
        <PackageVersion Include="Olve.MinimalApi" Version="0.32.2" />
        <PackageVersion Include="Olve.OpenRaster" Version="0.1.5" />
        <PackageVersion Include="Olve.Operations" Version="0.32.2" />
        <PackageVersion Include="Olve.Paths" Version="0.32.2" />
        <PackageVersion Include="Olve.Results" Version="0.32.2" />
        <PackageVersion Include="Olve.Utilities" Version="0.32.2" />
        <PackageVersion Include="Olve.Validation" Version="0.32.2" />
        <PackageVersion Include="OneOf" Version="3.0.271" />
        <PackageVersion Include="OneOf.SourceGenerator" Version="3.0.271" />
        <PackageVersion Include="ScottPlot" Version="5.0.55" />
        <PackageVersion Include="Scriban" Version="6.2.1" />
        <PackageVersion Include="Silk.NET.Assimp" Version="2.22.0" />
        <PackageVersion Include="Silk.NET.Input" Version="2.22.0" />
        <PackageVersion Include="Silk.NET.Maths" Version="2.22.0" />
        <PackageVersion Include="Silk.NET.OpenGL" Version="2.22.0" />
        <PackageVersion Include="Silk.NET.Windowing" Version="2.22.0" />
        <PackageVersion Include="Spectre.Console" Version="0.50.0" />
        <PackageVersion Include="StrictId" Version="1.2.0" />
        <PackageVersion Include="System.Drawing.Common" Version="9.0.8" />
        <PackageVersion Include="TUnit" Version="0.53.0" />
    </ItemGroup>
</Project>