<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TUnit"/>
        <PackageReference Include="Olve.Results.TUnit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Olve.Trains\Olve.Trains.csproj"/>
    </ItemGroup>
</Project>
