<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <RollForward>Major</RollForward>
        <PublishReadyToRun>false</PublishReadyToRun>
        <Nullable>enable</Nullable>
        <ImplicitUsings>true</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <TieredCompilation>false</TieredCompilation>
    </PropertyGroup>
    <ItemGroup>
        <None Update="assets\**\*">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Silk.NET.Input" Version="2.22.0" />
        <PackageReference Include="Silk.NET.OpenGL" Version="2.22.0" />
        <PackageReference Include="Silk.NET.Windowing" Version="2.22.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Olve.Engine3D\Olve.Engine3D.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="assets\" />
    </ItemGroup>

</Project>
