<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <PublishSelfContained>true</PublishSelfContained>
    </PropertyGroup>
    <ItemGroup>
        <None Update="assets\**\*" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Olve.Engine3D\Olve.Engine3D.csproj"/>
        <ProjectReference Condition="'$(Configuration)' == 'Debug'" Include="..\Olve.Engine3D.DebugServer\Olve.Engine3D.DebugServer.csproj"/>
    </ItemGroup>

</Project>
