<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="MemoryPack" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="Olve.OpenRaster" />
        <PackageReference Include="Olve.Paths" />
        <PackageReference Include="Olve.Results" />
        <PackageReference Include="Olve.Utilities" />
        <PackageReference Include="OneOf" />
        <PackageReference Include="OneOf.SourceGenerator" />
        <PackageReference Include="Silk.NET.Input" />
        <PackageReference Include="Silk.NET.Maths" />
        <PackageReference Include="Silk.NET.OpenGL" />
        <PackageReference Include="Silk.NET.Windowing" />
        <PackageReference Include="StbImageWriteSharp" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="GUI\Layout\ContentFit.cs" />
    </ItemGroup>

</Project>
