name: Push to master

on:
  push:
    branches:
      - master

permissions:
  actions: read
  pages: write
  id-token: write

concurrency:
  group: "deploy"
  cancel-in-progress: false

env:
  DOTNET_VERSION: 9.0.100
  MINIO_HOST: minio.lan
  MINIO_URL: http://minio.lan:9000
  MINIO_BUCKET: olve.trains
  TS_EXIT_NODE: tailscale-home

jobs:
  build:
    name: Build game and save in minio
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      # you can't set the exit-node name at 'up' time; so instead set it after
      # we've gotten up and running
      # https://github.com/tailscale/github-action/issues/123
      # https://github.com/tailscale/tailscale/issues/4152#issuecomment-1066126643
      - name: use named exit node in tailscale
        run: |
          timeout 5m sudo -E tailscale set --exit-node=${{ env.TS_EXIT_NODE }} --exit-node-allow-lan-access=true

      - name: Tailscale Verification
        run: |
          sudo tailscale netcheck
          sudo tailscale ip -4
          sudo tailscale status
          sudo tailscale ping -c 1 ${{ env.MINIO_HOST }}

      - name: Setup .env
        run: |
          echo "S3_URL=${{ env.MINIO_URL }}" >> ./src/Olve.Trains.AssetPipeline/.env
          echo "S3_BUCKET=${{ env.MINIO_BUCKET }}" >> ./src/Olve.Trains.AssetPipeline/.env
          echo "S3_KEY=${{ secrets.MINIO_ACCESS_KEY }}" >> ./src/Olve.Trains.AssetPipeline/.env
          echo "S3_SECRET=${{ secrets.MINIO_SECRET_KEY }}" >> ./src/Olve.Trains.AssetPipeline/.env
          echo "LOG_LEVEL=Debug" >> ./src/Olve.Trains.AssetPipeline/.env

      - name: Run asset pipeline
        shell: bash
        run: sh ./src/Olve.Trains.AssetPipeline/build.sh

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: .NET restore
        shell: bash
        run: dotnet restore

      - name: Build
        shell: bash
        run: dotnet build --no-restore -c Release /p:Version="1.0.0"

      - name: Publish
        shell: bash
        run: dotnet publish --no-restore -c Release /p:Version="1.0.0" --output ./publish

      - name: Minio Deploy
        uses: lovellfelix/minio-deploy-action@v1
        with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: 'olve-trains'
          source_dir: './publish'
          target_dir: 'releases/1.0.0'

      - name: Undo Tailscale
        run: sudo tailscale down

      - name: Exit status
        run: echo "Done"
