name: Push to master

on:
  push:
    branches:
      - master

permissions:
  actions: read
  pages: write
  id-token: write

concurrency:
  group: "deploy"
  cancel-in-progress: false

env:
  DOTNET_VERSION: 9.0.100
  S3_URL: http://minio:9000
  S3_BUCKET: olve.trains
  TS_EXIT_NODE: tailscale-home

jobs:
  bump-version:
    name: Bump version and create changelog with commitizen
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.cz.outputs.version }}
      changed: ${{ steps.version-changed.outputs.changed }}

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"

      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - id: version-changed
        name: Check if version changed
        run: |
          [[ $REVISION = $PREVIOUS_REVISION ]] && CHANGED="false" || CHANGED="true"
          echo "changed=$CHANGED" >> "$GITHUB_OUTPUT"
          [[ $CHANGED = "true" ]] && echo "::notice::Version changed ($PREVIOUS_REVISION -> $REVISION)" || echo "::notice::Version did not change"

      - name: Release
        id: release
        uses: softprops/action-gh-release@v2
        if: "${{ steps.version-changed.outputs.changed == 'true' }}"
        with:
          body_path: ${{ github.workspace }}/CHANGELOG.md
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tag_name: v${{ steps.cz.outputs.version }}

      - name: Echo release id
        if: "${{ steps.version-changed.outputs.changed == 'true' }}"
        run: echo "::notice::id=${{ steps.release.outputs.id }}"

  build:
    name: Build game and save in minio
    needs:
      - bump-version
    if: "${{ needs.bump-version.outputs.changed == 'true' }}"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
        
      - name: Tailscale Up
        run: sudo tailscale up

      - name: Setup .env
        run: |
          echo "S3_URL=${{ env.S3_URL }}" >> ./src/Olve.Trains.AssetPipeline/.env
          echo "S3_BUCKET=${{ env.S3_BUCKET }}" >> ./src/Olve.Trains.AssetPipeline/.env
          echo "S3_KEY=${{ secrets.MINIO_ACCESS_KEY }}" >> ./src/Olve.Trains.AssetPipeline/.env
          echo "S3_SECRET=${{ secrets.MINIO_SECRET_KEY }}" >> ./src/Olve.Trains.AssetPipeline/.env
          echo "LOG_LEVEL=Debug" >> ./src/Olve.Trains.AssetPipeline/.env


      - name: Run asset pipeline
        shell: bash
        run: sh ./src/Olve.Trains.AssetPipeline/build.sh

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: .NET restore
        shell: bash
        run: dotnet restore

      - name: Build
        shell: bash
        run: dotnet build --no-restore -c Release /p:Version="${{ needs.bump-version.outputs.version }}"

      - name: Publish
        shell: bash
        run: dotnet publish --no-restore -c Release /p:Version="${{ needs.bump-version.outputs.version }}" --output ./publish

      - name: Minio Deploy
        uses: lovellfelix/minio-deploy-action@v1
        with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: 'olve-trains'
          source_dir: './publish'
          target_dir: 'releases/${{ needs.bump-version.outputs.version }}'
